/**
 * Auto-generated by migrate_to_independent_ids.py
 * Este archivo mapea slugs de variantes a product IDs independientes.
 *
 * Usado como cache local para evitar llamadas innecesarias al backend.
 */

export const VARIANT_ID_MAPPING: Record<string, string> = {
  "azul-128gb": "MLC621083881",
  "natural-128gb": "MLC677194340",
  "negro-128gb": "MLC204267746",
  "azul-256gb": "MLC928744140",
  "natural-256gb": "MLC137702355",
  "negro-256gb": "MLC474475489",
  "azul-512gb": "MLC473630929",
  "natural-512gb": "MLC403211283",
  "negro-512gb": "MLC882941432",
};

/**
 * Construye la clave de búsqueda para el mapping
 */
export function buildMappingKey(variantSlugs: Record<string, string>): string {
  const color = variantSlugs.color || '';
  const capacidad = variantSlugs.capacidad || '';
  return `${color}-${capacidad}`;
}

/**
 * Intenta obtener el product ID desde el mapping local
 * @returns Product ID si existe en el mapping, null si no
 */
export function getVariantIdFromMapping(variantSlugs: Record<string, string>): string | null {
  const key = buildMappingKey(variantSlugs);
  return VARIANT_ID_MAPPING[key] || null;
}
